### ISSUE TITLE
TypeError: Cannot read property 'live' of undefined

### ISSUE THREAD

**Issue by pfrazee** [joehand/dat-next#111]
I started getting this within https://github.com/pfrazee/dathttpd. It was working for a while, then this started happening. The dat-next processes are children called by the parent. I dont *think* it's my doing. I suspect that the updateDownload interval is getting called before start is.

Here's the dump:

```
TypeError: Cannot read property 'live' of undefined
    at updateDownload (/Users/paulfrazee/dathttpd/node_modules/dat-next/lib/download.js:116:30)
    at Timeout._repeat (/Users/paulfrazee/dathttpd/node_modules/dat-next/lib/download.js:45:16)
    at Timeout.wrapper [as _onTimeout] (timers.js:417:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by okdistribute** [comment]
Fixed by https://github.com/joehand/dat-next/pull/109

**Comment by okdistribute** [comment]
Merged but not published

**Comment by pfrazee** [comment]
Ah cool, thanks!

**Comment by pfrazee** [comment]
Fixed
