### ISSUE TITLE
Error: Could not locate data

### ISSUE THREAD

**Issue by pfrazee** [joehand/dat-next#122]
I'm getting this error when I run dat-next on a folder:

```
~/my/apps/hakll ~/my/dat-next/cli.js 
dat://a60bddb8ea1e9bf4ee510cbd864fd4133175c3a1f09d7935ce0a429dfd789018
Syncing Archive: 304 files (2.1 MB)

Waiting for Connections...

Importing 2320 files to Archive
[==========--------------------------------] 2.1 MB / 8.6 MB
1.2 MB/s

ADD: /node_modules/browser-resolve/index.js
[------------------------------------------] 0 B / 9.3 KB
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: Could not locate data
    at /Users/paulfrazee/my/dat-next/node_modules/dat-storage/index.js:50:30
    at loop (/Users/paulfrazee/my/dat-next/node_modules/dat-storage/index.js:108:19)
    at /Users/paulfrazee/my/dat-next/node_modules/dat-storage/index.js:75:5
    at /Users/paulfrazee/my/dat-next/node_modules/hypercore/index.js:967:5
    at onread (/Users/paulfrazee/my/dat-next/node_modules/random-access-file/index.js:107:25)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:627:17)
```

**Comment by joehand** [comment]
This is a dat-storage error mafintosh is aware of and working on (possible related to the `latest` option in hyperdrive).
